//! Golden values generated by executing the original TS formulas in Node
//! (V8 doubles). Tolerance 1e-9 degrees (~0.1 mm) covers libm ULP differences
//! between V8 and Rust.

use terronnd::geodesy::{
    bearing_wgs84, distance_wgs84, normalize_heading, project_wgs84, wgs84_to_pixel_coordinate,
};

const TOL: f64 = 1e-9;

fn assert_close(actual: f64, expected: f64) {
    assert!(
        (actual - expected).abs() < TOL,
        "expected {expected}, got {actual} (delta {})",
        (actual - expected).abs()
    );
}

#[test]
fn project_short_distance() {
    let (lat, lon) = project_wgs84(47.26081, 11.34966, 260.0, 10.0 * 1852.0);
    assert_close(lat, 47.231634283379918);
    assert_close(lon, 11.108105794295565);
}

#[test]
fn project_medium_distance() {
    let (lat, lon) = project_wgs84(47.26081, 11.34966, 260.0, 100.0 * 1852.0);
    assert_close(lat, 46.946368667779765);
    assert_close(lon, 8.9466582398376939);
}

#[test]
fn project_visibility_range_north() {
    let (lat, lon) = project_wgs84(47.26081, 11.34966, 0.0, 800.0 * 1852.0);
    assert_close(lat, 60.585137999262727);
    assert_close(lon, 11.34966);
}

#[test]
fn project_across_antimeridian() {
    let (lat, lon) = project_wgs84(-10.5, 179.2, 90.0, 300.0 * 1852.0);
    assert_close(lat, -10.459648108814481);
    assert_close(lon, -175.71872495874433);
}

#[test]
fn project_over_north_pole() {
    let (lat, lon) = project_wgs84(85.0, 10.0, 0.0, 800.0 * 1852.0);
    assert_close(lat, 81.675672000737308);
    assert_close(lon, -170.0);
}

#[test]
fn bearing_keeps_the_ts_180_offset() {
    // Innsbruck -> Munich: true initial bearing is ~14.85°; the TS function
    // returns bearing + 180° and every caller compensates — kept identical.
    assert_close(bearing_wgs84(47.26081, 11.34966, 48.35378, 11.78609), 194.85119547295631);
}

#[test]
fn distance_nautical_miles() {
    assert_close(distance_wgs84(47.26081, 11.34966, 48.35378, 11.78609), 67.941132454759199);
    assert_close(distance_wgs84(-10.5, 179.8, -10.5, -179.8), 23.614073726463719);
}

#[test]
fn normalize_heading_wraps() {
    assert_close(normalize_heading(370.0), 10.0);
    assert_close(normalize_heading(-10.0), 350.0);
    assert_close(normalize_heading(720.5), 0.5);
}

#[test]
fn pixel_coordinate_simple() {
    // 10x10 world map covering (46,10)..(48,12), ego at its center pixel (5,5),
    // ground truth at (47,11). One pixel = 0.2 degrees in both axes.
    let (x, y) = wgs84_to_pixel_coordinate(
        47.0, 47.0, 11.0, 47.0, 11.0, 46.0, 10.0, 48.0, 12.0, 10, 10, 5.0, 5.0,
    );
    assert_eq!((x, y), (5, 5));

    // 0.4 degrees north-east of ground truth -> +2 px east, -2 px north (y up is north)
    let (x, y) = wgs84_to_pixel_coordinate(
        47.0, 47.4, 11.4, 47.0, 11.0, 46.0, 10.0, 48.0, 12.0, 10, 10, 5.0, 5.0,
    );
    assert_eq!((x, y), (7, 3));
}

#[test]
fn pixel_coordinate_antimeridian_wrap_is_fixed() {
    // World map straddling the antimeridian: (-12,178)..(-9,-178) => 4 deg of
    // longitude across the wrap on a 40-wide map (0.1 deg/px), 30-high (0.1 deg/px).
    // Ground truth at (-10.5, 179.9), ego pixel (20, 15).
    // A point at longitude -179.9 is +0.2 deg east across the wrap => +2 px.
    let (x, y) = wgs84_to_pixel_coordinate(
        -10.5, -10.5, -179.9, -10.5, 179.9, -12.0, 178.0, -9.0, -178.0, 40, 30, 20.0, 15.0,
    );
    assert_eq!((x, y), (22, 15));

    // And a point at 179.7 is -2 px west (no wrap crossing for the delta sign).
    let (x, y) = wgs84_to_pixel_coordinate(
        -10.5, -10.5, 179.7, -10.5, 179.9, -12.0, 178.0, -9.0, -178.0, 40, 30, 20.0, 15.0,
    );
    assert_eq!((x, y), (18, 15));

    // Mirror case: ground truth just west of the wrap, point just east of it.
    let (x, y) = wgs84_to_pixel_coordinate(
        -10.5, -10.5, 179.9, -10.5, -179.9, -12.0, 178.0, -9.0, -178.0, 40, 30, 20.0, 15.0,
    );
    assert_eq!((x, y), (18, 15));
}
