//! Golden-frame regression: every scenario in `testdata/scenarios` must render
//! pixel-exact against its `testdata/golden` reference. The goldens were
//! originally generated by the SimBridge terrain-rust `render_scene` tool and
//! REGENERATED from this crate when the extraction math was optimized (same
//! projection, numerically equivalent but not bitwise — see README).
//!
//! Rendering goes through the production data path: `terrain2.map` (converted
//! on the fly from the v1 database when missing) and the `RegionManager`
//! range-sized raster. When the data layer was redesigned, every L0 scenario
//! was additionally rendered through the deleted v1 800 nm monolith and
//! asserted bit-identical (the faithfulness proof); the goldens pinned then
//! carry that guarantee forward.
//!
//! Needs a real `terrain.map`: set `SIMBRIDGE_TERRAIN_MAP` or place it at the
//! repo-root `cache/terrain.map`; the test is skipped otherwise.
//!
//! `GOLDEN_REGENERATE=1` switches to regeneration: each scenario is compared
//! against the existing golden (tolerance report on stdout), then the golden
//! PNGs/thresholds are rewritten from the current implementation.

use std::io::BufWriter;
use std::path::{Path, PathBuf};

use terronnd::block_map::extract_block_maxima;
use terronnd::convert::{check_v2, convert_v1_to_v2};
use terronnd::elevation_map::metres_per_pixel;
use terronnd::fileformat::TerrainMap;
use terronnd::fileformat_v2::TerrainMapV2;
use terronnd::geodesy::{project_wgs84, NM_TO_METRES};
use terronnd::jsmath::js_round;
use terronnd::nd_render::{
    absolute_cut_off_altitude, compute_render_stats, compute_thresholds, PreparedRender,
    TerrainLevelMode, Thresholds,
};
use terronnd::patterns::{ARC_PATTERN, SCANLINE_PATTERN};
use terronnd::region::{RegionInputs, RegionManager};
use terronnd::state::{nd_map_geometry, AircraftStatus, NdMapGeometry, Side};
use terronnd::statistics::elevation_histogram;
use terronnd::vd_render::{
    extract_elevation_profile, render_vertical_display, vd_range_from_nd, ElevationProfileConfig,
    VD_PROFILE_HEIGHT, VD_PROFILE_WIDTH,
};
use terronnd::worldmap::WorldMap;

fn database_path() -> Option<String> {
    if let Ok(path) = std::env::var("SIMBRIDGE_TERRAIN_MAP") {
        if Path::new(&path).is_file() {
            return Some(path);
        }
    }
    let repo_root_cache = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../../cache/terrain.map");
    if repo_root_cache.is_file() {
        return Some(repo_root_cache.to_string_lossy().into_owned());
    }
    None
}

/// The repo-root `cache/terrain2.map` the build also produces; converted from
/// the v1 database here when missing or invalid (a quick repack).
fn ensure_v2_database(v1_path: &str) -> String {
    let v2_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../../cache/terrain2.map");
    let v2_str = v2_path.to_string_lossy().into_owned();
    if v2_path.is_file() && check_v2(&v2_str) {
        return v2_str;
    }

    eprintln!("converting {v1_path} -> {v2_str} (one-time)");
    std::fs::create_dir_all(v2_path.parent().unwrap()).unwrap();
    let v1 = TerrainMap::open(v1_path).expect("open v1 terrain.map");
    let part = format!("{v2_str}.part");
    {
        let file = std::fs::File::create(&part).unwrap();
        let mut out = BufWriter::with_capacity(1 << 20, file);
        convert_v1_to_v2(&v1, &mut out, |_, _| {}).expect("v1 -> v2 conversion");
    }
    if v2_path.is_file() {
        std::fs::remove_file(&v2_path).unwrap();
    }
    std::fs::rename(&part, &v2_path).unwrap();
    v2_str
}

fn decode_png_rgba(path: &Path) -> (usize, usize, Vec<u8>) {
    let mut decoder = png::Decoder::new(std::fs::File::open(path).unwrap());
    decoder.set_transformations(png::Transformations::EXPAND | png::Transformations::STRIP_16);
    let mut reader = decoder.read_info().unwrap();
    let mut buf = vec![0u8; reader.output_buffer_size()];
    let info = reader.next_frame(&mut buf).unwrap();
    buf.truncate(info.buffer_size());

    if info.color_type == png::ColorType::Rgb {
        let mut rgba = Vec::with_capacity(buf.len() / 3 * 4);
        for px in buf.chunks_exact(3) {
            rgba.extend_from_slice(px);
            rgba.push(255);
        }
        buf = rgba;
    } else {
        assert_eq!(info.color_type, png::ColorType::Rgba, "{path:?} color type");
    }
    (info.width as usize, info.height as usize, buf)
}

fn write_png_rgba(path: &Path, width: usize, height: usize, rgba: &[u8]) {
    let file = std::fs::File::create(path).unwrap();
    let mut encoder = png::Encoder::new(BufWriter::new(file), width as u32, height as u32);
    encoder.set_color(png::ColorType::Rgba);
    encoder.set_depth(png::BitDepth::Eight);
    encoder
        .write_header()
        .unwrap()
        .write_image_data(rgba)
        .unwrap();
}

fn mode_value(mode: TerrainLevelMode) -> u8 {
    match mode {
        TerrainLevelMode::PeaksMode => 0,
        TerrainLevelMode::Warning => 1,
        TerrainLevelMode::Caution => 2,
    }
}

/// (differing pixel count, max channel delta)
fn diff_rgba(a: &[u8], b: &[u8]) -> (usize, u8) {
    let differing = a
        .chunks_exact(4)
        .zip(b.chunks_exact(4))
        .filter(|(x, y)| x != y)
        .count();
    let max_delta = a
        .iter()
        .zip(b.iter())
        .map(|(x, y)| x.abs_diff(*y))
        .max()
        .unwrap_or(0);
    (differing, max_delta)
}

struct Rendered {
    geometry: NdMapGeometry,
    frame: Vec<u8>,
    thresholds: Thresholds,
    vd_frame: Option<Vec<u8>>,
}

/// The full per-scenario render — one code path shared by both world sources.
fn render_scenario(world: &WorldMap, status: &AircraftStatus) -> Rendered {
    let efis = status.efis(Side::Left).clone();
    let geometry = nd_map_geometry(efis.arc_mode, status.vertical_display_required());
    let mpp = metres_per_pixel(efis.nd_range, &geometry, efis.arc_mode);
    let blocks = extract_block_maxima(
        world,
        status.latitude,
        status.longitude,
        status.heading,
        &geometry,
        mpp,
        efis.arc_mode,
    );
    let histogram = elevation_histogram(&blocks);
    let cut_off = absolute_cut_off_altitude(
        world,
        status.latitude,
        status.longitude,
        status.altitude,
        status.runway_data_valid,
        status.runway_latitude,
        status.runway_longitude,
    );
    let stats = compute_render_stats(
        &histogram,
        status.altitude,
        status.vertical_speed,
        status.gear_is_down,
        cut_off,
    );
    let pattern: &[u8] = if status.scanline_mode() {
        &SCANLINE_PATTERN[..]
    } else {
        &ARC_PATTERN[..]
    };
    let prepared = PreparedRender::from_blocks(&blocks, &geometry, &stats);
    let mut frame = vec![0u8; geometry.width * geometry.height * 4];
    prepared.paint_rows(pattern, geometry.width, &mut frame, 0, geometry.height);
    let thresholds = compute_thresholds(&stats);

    // VD frame (manual-azimuth path, like render_scene) when the scenario
    // renders one
    let vd_active = status.vertical_display_required()
        && efis.terr_on_vd
        && (efis.efis_mode == 2 || efis.efis_mode == 3);
    let vd_frame = if vd_active {
        let azim_end = project_wgs84(
            status.latitude,
            status.longitude,
            status.manual_azim_degrees,
            160.0 * NM_TO_METRES,
        );
        let profile_config = ElevationProfileConfig {
            path_width: 1.0,
            waypoints: vec![azim_end],
            range: vd_range_from_nd(efis.nd_range, efis.arc_mode),
            track_changes_significantly_at_distance: -1.0,
            fms_path_used: false,
        };
        let profile = extract_elevation_profile(
            world,
            status.latitude,
            status.longitude,
            &profile_config,
        );
        Some(render_vertical_display(
            &profile,
            efis.vd_range_lower,
            efis.vd_range_upper,
            -1.0,
        ))
    } else {
        None
    };

    Rendered {
        geometry,
        frame,
        thresholds,
        vd_frame,
    }
}

#[test]
fn scenarios_render_pixel_exact() {
    let Some(db_path) = database_path() else {
        eprintln!("no terrain.map found (SIMBRIDGE_TERRAIN_MAP / cache/terrain.map) — skipping");
        return;
    };
    let regenerate = std::env::var("GOLDEN_REGENERATE").is_ok();

    // the production data path: terrain2.map + the capability-sized region
    // raster
    let v2_path = ensure_v2_database(&db_path);

    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    let scenario_dir = manifest.join("testdata/scenarios");
    let golden_dir = manifest.join("testdata/golden");

    let mut scenario_paths: Vec<PathBuf> = std::fs::read_dir(&scenario_dir)
        .unwrap()
        .map(|e| e.unwrap().path())
        .filter(|p| p.extension().is_some_and(|e| e == "json"))
        .collect();
    scenario_paths.sort();
    assert!(!scenario_paths.is_empty(), "no scenarios found");

    let mut compared = 0usize;
    for scenario_path in scenario_paths {
        let name = scenario_path.file_stem().unwrap().to_string_lossy().into_owned();
        let golden_path = golden_dir.join(format!("{name}.png"));
        if !regenerate && !golden_path.is_file() {
            eprintln!("{name}: no golden frame — skipping");
            continue;
        }

        let status: AircraftStatus =
            serde_json::from_str(&std::fs::read_to_string(&scenario_path).unwrap()).unwrap();

        // a fresh manager per scenario: the raster is sized by the aircraft
        // capability (vertical-display flag, LATCHED once seen), and mixing
        // A380X and A32NX scenarios through one manager would render the
        // A32NX ones from an A380X-sized rect no real aircraft ever uses
        let mut region =
            RegionManager::new(TerrainMapV2::open(&v2_path).expect("open terrain2.map"));
        let inputs = RegionInputs::from_status(&status);
        let world = region.update_sync(&inputs).expect("region snapshot");
        let rendered = render_scenario(&world, &status);
        let geometry = rendered.geometry;

        // golden may be the bare ND region or a full composited screen frame
        // (ND blitted at (offset_x, 128)) — crop in the latter case
        let golden = if golden_path.is_file() {
            let (golden_w, golden_h, golden) = decode_png_rgba(&golden_path);
            Some(if golden_w == geometry.width && golden_h == geometry.height {
                golden
            } else if golden_w >= geometry.width + geometry.offset_x
                && golden_h >= geometry.height + 128
            {
                let stride = golden_w * 4;
                let mut cropped = Vec::with_capacity(geometry.width * geometry.height * 4);
                for y in 0..geometry.height {
                    let start = (y + 128) * stride + geometry.offset_x * 4;
                    cropped.extend_from_slice(&golden[start..start + geometry.width * 4]);
                }
                cropped
            } else {
                panic!(
                    "{name}: golden is {golden_w}x{golden_h}, rendered {}x{}",
                    geometry.width, geometry.height
                );
            })
        } else {
            None
        };

        let thresholds_path = golden_dir.join(format!("{name}.thresholds.json"));
        let vd_path = golden_dir.join(format!("{name}.vd.png"));
        let thresholds = rendered.thresholds;

        if regenerate {
            // tolerance report against the previous goldens, then rewrite
            if let Some(golden) = &golden {
                let (differing, max_delta) = diff_rgba(&rendered.frame, golden);
                let total = geometry.width * geometry.height;
                println!(
                    "{name}: ND {differing}/{total} differing px ({:.4}%), max channel delta {max_delta}",
                    differing as f64 / total as f64 * 100.0
                );
            }
            write_png_rgba(&golden_path, geometry.width, geometry.height, &rendered.frame);

            let json = serde_json::json!({
                "minimumElevation": js_round(thresholds.minimum_elevation) as i64,
                "minimumElevationMode": mode_value(thresholds.minimum_elevation_mode),
                "maximumElevation": js_round(thresholds.maximum_elevation) as i64,
                "maximumElevationMode": mode_value(thresholds.maximum_elevation_mode),
            });
            std::fs::write(
                &thresholds_path,
                serde_json::to_string_pretty(&json).unwrap() + "\n",
            )
            .unwrap();

            if let Some(vd_frame) = &rendered.vd_frame {
                if vd_path.is_file() {
                    let (_, _, vd_golden) = decode_png_rgba(&vd_path);
                    let (differing, max_delta) = diff_rgba(vd_frame, &vd_golden);
                    println!(
                        "{name}: VD {differing}/{} differing px, max channel delta {max_delta}",
                        VD_PROFILE_WIDTH * VD_PROFILE_HEIGHT
                    );
                }
                write_png_rgba(&vd_path, VD_PROFILE_WIDTH, VD_PROFILE_HEIGHT, vd_frame);
            }
            compared += 1;
            continue;
        }

        let golden = golden.unwrap();
        let (differing, _) = diff_rgba(&rendered.frame, &golden);
        assert_eq!(differing, 0, "{name}: {differing} differing ND pixels");

        // threshold metadata
        if thresholds_path.is_file() {
            let golden_thresholds: serde_json::Value =
                serde_json::from_str(&std::fs::read_to_string(&thresholds_path).unwrap()).unwrap();
            assert_eq!(
                golden_thresholds["minimumElevation"].as_i64().unwrap(),
                js_round(thresholds.minimum_elevation) as i64,
                "{name}: minimumElevation"
            );
            assert_eq!(
                golden_thresholds["minimumElevationMode"].as_i64().unwrap() as u8,
                mode_value(thresholds.minimum_elevation_mode),
                "{name}: minimumElevationMode"
            );
            assert_eq!(
                golden_thresholds["maximumElevation"].as_i64().unwrap(),
                js_round(thresholds.maximum_elevation) as i64,
                "{name}: maximumElevation"
            );
            assert_eq!(
                golden_thresholds["maximumElevationMode"].as_i64().unwrap() as u8,
                mode_value(thresholds.maximum_elevation_mode),
                "{name}: maximumElevationMode"
            );
        }

        // vertical display golden
        if vd_path.is_file() {
            let vd_frame = rendered.vd_frame.as_ref().expect("VD golden exists but no VD rendered");
            let (vd_w, vd_h, vd_golden) = decode_png_rgba(&vd_path);
            assert_eq!((vd_w, vd_h), (VD_PROFILE_WIDTH, VD_PROFILE_HEIGHT), "{name}: vd size");
            let (vd_differing, _) = diff_rgba(vd_frame, &vd_golden);
            assert_eq!(vd_differing, 0, "{name}: {vd_differing} differing VD pixels");
        }

        compared += 1;
        println!("{name}: PIXEL-EXACT");
    }
    assert!(compared >= 6, "expected to compare at least 6 scenarios, got {compared}");
}
